#--------zinit installer--------#
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
  command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
  command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f" || \
    print -P "%F{160}▓▒░ The clone has failed.%f"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

#--------zinit plugins--------#
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting
zinit light romkatv/powerlevel10k

#--------plugin setting--------#
#Enabnle Powerlevel10k
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#--------zsh setting--------#
#Alias
alias ls="ls -GF --color=auto" #lsのカスタム(フォルダに/引いたり...)
alias la='ls -la' #省略
alias ytm='youtube-dl --extract-audio --audio-format mp3' #長いから省略

#Path
export PATH="$PATH:/usr/local/Cellar/llvm/10.0.0_3/bin" #for mac clangd path
export PATH="/usr/local/sbin:$PATH"

#History and complete
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt share_history         # コマンド履歴ファイルを共有する
setopt hist_ignore_all_dups # ヒストリに追加されるコマンド行が古いものと同じなら古いものを削除
setopt hist_ignore_space # スペースで始まるコマンド行はヒストリリストから削除
setopt hist_ignore_dups # 重複を記録しない
setopt hist_reduce_blanks    # 余分な空白は詰めて記録
setopt hist_no_store         # historyコマンドは履歴に登録しない
setopt hist_expand # 補完時にヒストリを自動的に展開
setopt append_history        # 履歴を追加 (毎回 .zsh_history を作るのではなく)
setopt inc_append_history    # 履歴をインクリメンタルに追加
zstyle ':completion:*:default' menu select #補間メニュー

#Press C-r to complete from past command with fzf
bindkey -v #Like Vim
bindkey '\e[3~' delete-char
bindkey '^r' select-history
function select-history() {
  BUFFER=$(history -n -r 1 | fzf --no-sort +m --query "$LBUFFER" --prompt="History > ")
  CURSOR=$#BUFFER
}
zle -N select-history

#Go to a directory been to before
bindkey '^u' fzf-cdr
#cdr
if [[ -n $(echo ${^fpath}/chpwd_recent_dirs(N)) && -n $(echo ${^fpath}/cdr(N)) ]]; then
  autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
  add-zsh-hook chpwd chpwd_recent_dirs
  zstyle ':completion:*' recent-dirs-insert both
  zstyle ':chpwd:*' recent-dirs-default true
  zstyle ':chpwd:*' recent-dirs-max 1000
  zstyle ':chpwd:*' recent-dirs-file "$HOME/.cache/chpwd-recent-dirs"
fi
#fzf
function fzf-cdr () {
  local selected_dir="$(cdr -l | sed 's/^[0-9]\+ \+//' | fzf --prompt="cdr >" --query "$LBUFFER")"
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
}
zle -N fzf-cdr


#View
setopt list_packed #補間候補を詰める
setopt list_types #補間候補一覧で種類を区別
autoload -Uz compinit #補完&色つけ
compinit

#Others
setopt auto_cd #フォルダ名だけで移動
setopt auto_pushd #移動履歴
setopt correct #コマンド訂正

#Load Powerlevel10k configure
[[ ! -f ~/Dotfiles/home/p10k.zsh ]] || source ~/Dotfiles/home/p10k.zsh
