############################
# .zshenv | Made by NULLCT #
############################
export XDG_CONFIG_HOME="$HOME/.config" #.config/* 系の設定ファイルパス指定
export PATH="/usr/local/opt/llvm/bin:$PATH" #clangd
export TERM=xterm-256color
